# project name
name: django-htmx

services:
  web:
    # directory containing Dockerfile
    build: ./app
    # start django server
    command: python manage.py runserver 0.0.0.0:8000
    # forward container port 8000 for localhost 8000 port
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    # wait for DB container up
    depends_on:
      - db
      - memcached

  db:
    # use Postgres image ver. 17
    image: postgres:17
    # mount postgres-data to dir /var/lib/postgresql@17/data of DB container
    volumes:
      - postgres-data:/var/lib/postgresql@17/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - '127.0.0.1:5435:5432'

  memcached:
    image: memcached:1.6.34

volumes:
  # declare postgres-data volume for storing Postgres data
  postgres-data: